version: '3'

services:
    web:
        build: .
        command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000 # new
        environment: 
            - SECRET_KEY=xa4bc!j$$yw(-d&#$$8u)ctezs__n)kf&1+dy+f=-31ij!@8pb%%'
            - DEBUG=1
            - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51HUq9QFgv9HUgZUthzVgOpBfu4RABpQTii5ICcGKdmJHsQCLugiHEtGj53SoaDAgbDEIQ6NJlYWjUSAisevNMuUc00224e8amH
            - STRIPE_TEST_SECRET_KEY=sk_test_51HUq9QFgv9HUgZUtMm92sWky63CTDgjDDZWqwua4DZGHj1c5pRTicgLsAmaTa9NGuNKnEYi3aN6Id4x89amjBj0A00MXmdHWJa
            - ENVIRONMENT=development
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres
        ports: 
            - "5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres  
          - POSTGRES_PASSWORD=postgres

volumes:
    postgres_data: